import type { AtomsLoggerOptions, AtomsLoggerOptionsInState } from '../types/atoms-logger.js';

// eslint-disable-next-line complexity -- it's a simple conversion function
export function atomsLoggerOptionsToState(
  options: AtomsLoggerOptions = {},
): AtomsLoggerOptionsInState {
  const {
    enabled = true,
    domain,
    shouldShowPrivateAtoms = false,
    shouldShowAtom,
    logger = console,
    groupTransactions = true,
    groupEvents = false,
    indentSpaces = 0,
    formattedOutput = true,
    colorScheme = 'default',
    stringifyLimit = 50,
    stringifyValues = true,
    stringify,
    showTransactionNumber = true,
    showTransactionEventsCount = true,
    showTransactionLocaleTime = false,
    showTransactionElapsedTime = true,
    collapseTransactions = false,
    collapseEvents = false,
    ownerStackLimit = 2,
    getOwnerStack,
    getComponentDisplayName,
    synchronous = false,
    transactionDebounceMs = 250,
    requestIdleCallbackTimeoutMs = 250,
    maxProcessingTimeMs = 16,
  } = options;
  return {
    enabled,
    domain,
    shouldShowPrivateAtoms,
    shouldShowAtom,
    logger,
    groupTransactions,
    groupEvents,
    indentSpaces,
    indentSpacesDepth1:
      indentSpaces <= 0 ? '' : Array.from({ length: indentSpaces }, () => ' ').join(''),
    indentSpacesDepth2:
      indentSpaces <= 0 ? '' : Array.from({ length: indentSpaces * 2 }, () => ' ').join(''),
    formattedOutput,
    colorScheme,
    stringifyLimit,
    stringifyValues,
    stringify,
    showTransactionNumber,
    showTransactionEventsCount,
    showTransactionLocaleTime,
    showTransactionElapsedTime,
    collapseTransactions,
    collapseEvents,
    ownerStackLimit,
    getOwnerStack,
    getComponentDisplayName,
    transactionDebounceMs: synchronous ? -1 : transactionDebounceMs,
    requestIdleCallbackTimeoutMs: synchronous ? -1 : requestIdleCallbackTimeoutMs,
    maxProcessingTimeMs: synchronous ? -1 : maxProcessingTimeMs,
  };
}
