export const DEFAULT_ENABLED = true;
export const DEFAULT_SHOULD_SHOW_PRIVATE_ATOMS = false;
export const DEFAULT_SYNCHRONOUS = false;
export const DEFAULT_TRANSACTION_DEBOUNCE_MS = 250;
export const DEFAULT_REQUEST_IDLE_CALLBACK_TIMEOUT_MS = 250;
export const DEFAULT_MAX_PROCESSING_TIME_MS = 16;
